# Generated by Django 3.2.15 on 2022-08-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201110_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='null', upload_to='documents/events/'),
        ),
    ]
